# -*- mode: ruby -*-
# vi: set ft=ruby :

# v1.local
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.synced_folder "./", "/vagrant", type: "virtualbox"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "192.168.68.8"
  config.vm.hostname = "v1.local"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  #config.vm.provision "shell", inline: <<-SHELL
   #  apt-get update
   #SHELL
end
